export const Routes = {
    root: "/",
    app: {
        user: {
            dashboard: "/user/dashboard",
            messages: "/user/messages",
            jobs: "/user/jobs",
            applications: "/user/applications",
            marketplace: "/user/market-place",
            telehealth: "/user/tele-health",
            profile: "/user/profile",
            settings: "/user/settings",
        },
        agency: {
            dashboard: "/agency/dashboard",
            messages: "/agency/messages",
            jobs: "/agency/jobs",
            applications: "/agency/applications",
            marketplace: "/agency/market-place",
            telehealth: "/agency/tele-health",
            profile: "/agency/profile",
            settings: "/agency/settings",
        },
    },
    auth: {
        login: "/auth/login",
        signup: "/auth/signup",
        verifyContact: "/auth/verify-contact",
        joinType: "/auth/join-type",
        profession: "/auth/profession",
        certifications: "/auth/certifications",
        documents: "/auth/documents",
        welcome: "/auth/welcome",
        organizationName: "/auth/organization-name",
        organizationType: "/auth/organization-type",
        organizationInterests: "/auth/organization-interests",
        forgotPassword: "/auth/forgot-password",
        resetPassword: "/auth/reset-password",
    },
};
