import { useEffect } from "react"
import { useNavigate, useSearchParams } from "react-router"
import { Routes } from "@/routes/constants"
import { useSignupWizard } from "@/utils/auth/context/SignupWizardContext"

/**
 * Landing page for an agency's "invite team member" link. Not linked from anywhere
 * in the public UI — only the link generated by the agency Team invite dialog points
 * here. Flags the in-progress signup as a professional (adds the Availability step)
 * and hands off to the normal signup form.
 */
export default function ProfessionalInvitePage() {
  const navigate = useNavigate()
  const [searchParams] = useSearchParams()
  const { setJoinType, setIsProfessional, setFullName, setEmail } = useSignupWizard()

  useEffect(() => {
    const name = searchParams.get("name")
    const email = searchParams.get("email")
    if (name) setFullName(name)
    if (email) setEmail(email)
    setJoinType("individual")
    setIsProfessional(true)
    navigate(Routes.auth.signup, { replace: true })
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  return null
}
